Test environment for users microservice
O-rv735/node-taxi pull request #21
Opened 2024-09-09 12:05 UTC by foobazdev

1. Configure jest config for unit tests
2. Configure jest and docker compose for e2e tests
3. Create script for generation .env files
4. Update README.md

2024-09-09 14:16 UTC, M-Ziusko requested changes

2024-09-09 14:16 UTC, M-Ziusko commented on backend/package.json
> +    "install:all": "npm i && (cd users && npm i && npx prisma generate)",
add postinstall script for npx prisma generate

2024-09-09 14:16 UTC, M-Ziusko commented on backend/users/src/users/users.controller.ts
> +    if (Object.keys(result).length === 0) {
```suggestion
    
    if (!Object.keys(result).length) {
```

2024-09-09 14:16 UTC, M-Ziusko commented on backend/users/src/users/users.controller.ts
> +    }
Should be deleted cause in service we did same job

2024-09-09 14:16 UTC, M-Ziusko commented on backend/users/src/users/users.service.ts
> +    }
Should be added as well for PUT :id & DELETE :id

2024-09-09 14:16 UTC, M-Ziusko commented on backend/users/test/truncate-tables.util.ts
> +    console.log({ error });
```suggestion
    console.log({ truncateTablesError });
```

2024-09-09 14:16 UTC, M-Ziusko commented on backend/users/test/users.e2e-spec.ts
> +      }));
I would love to use async/await here as well

2024-09-09 14:16 UTC, M-Ziusko commented on test/docker-compose.yml
> +      - PGPORT=${POSTGRES_PORT}
```suggestion
```

2024-09-10 11:36 UTC, foobazdev commented on backend/users/src/users/users.service.ts
> +    }
It is works with Prisma interception filter

2024-09-10 11:38 UTC, foobazdev commented on test/docker-compose.yml
> +      - PGPORT=${POSTGRES_PORT}
It is necessary  to run postgres on specific port, in this case 5433

2024-09-10 11:57 UTC, M-Ziusko requested changes

2024-09-10 11:57 UTC, M-Ziusko commented on backend/users/test/util/truncate-tables.util.ts
> +    .filter((name) => name !== '_prisma_migrations')
Move to query on line 8

2024-09-10 11:57 UTC, M-Ziusko commented on backend/users/test/util/truncate-tables.util.ts
> +    .map((name) => `"public"."${name}"`)
```suggestion
    .map(({ tablename }) => `"public"."${tablename}"`)
```

2024-09-10 11:57 UTC, M-Ziusko commented on backend/users/src/users/users.service.ts
> +  async update(id: string, data: UpdateUserDto) {
Do we need async here?

2024-09-10 11:57 UTC, M-Ziusko commented on backend/users/src/users/users.service.ts
> +    }
Discussed offline

2024-09-10 11:57 UTC, M-Ziusko commented on backend/users/test/users.e2e-spec.ts
> +  });
I think we should make sure that our schanges are applyed

2024-09-10 11:57 UTC, M-Ziusko commented on backend/users/test/users.e2e-spec.ts
> +  it('/users:id (PATCH) should return 400 if user does not exists', async () => {
```suggestion
  it('/users:id (PATCH) should return 404 if user does not exists', async () => {
```

2024-09-10 12:00 UTC, M-Ziusko commented on backend/users/test/util/truncate-tables.util.ts
> +    .map((name) => `"public"."${name}"`)
Add cashing for tables list

2024-09-10 12:18 UTC, M-Ziusko approved these changes

2024-09-10 12:18 UTC, merged